### PR TITLE
Fix issues #9, #10, and #12

### PR DESCRIPTION
**Pull request by texadactyl**
It turns out that using the -fcommon parameter renders  ```gcc``` tolerant of multiple definitions and provides the required automatic merging into a common block.  In the past, this was the default.  Currently, -fno_common is the default (makes sense).

If this repository receives any maintenance in the future, I would recommend that all of the *.h files be reviewed for copying definitions to a new global.c file and the references in the *.h files should be tagged as "extern".

### CODE REVIEW

**Comment by texadactyl** [comment]
ALSO - there are a lot of ```gcc``` warnings which should be reviewed!

**Comment by david-macmahon** [comment]
Nice sleuthing on the `-fcommon` flag @texadactyl!  I think we could entirely remove the reference to PSRsoft (although interesting, I think it's superfluous for `bl_sigproc`).

**Comment by texadactyl** [comment]
@david-macmahon 
The reference to PSRsoft was there originally so I guessed that the maintainers of this repository wanted to keep this historical note.

**Comment by texadactyl** [comment]
@david-macmahon Sorry to be a nag but this should be merged.

**Review by david-macmahon — COMMENTED** [review]
The explicit `-fcommon` flag is a great idea for solving #10, but I think it would be preferable to add this flag to `AM_CXXFLAGS` and `AM_CFLAGS` rather than `CXXFLAGS` and `CFLAGS`.  See [this automake FAQ](https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html) for more info.

It would also be good to ensure that the `-fcommon` flag gets included in `AM_CFLAGS` even if `X$haveopen != Xyes` (i.e. even if `AX_OPENMP` does not find what to seeks).  It looks like the current approach doesn't add it in that case.

**Comment by texadactyl** [comment]
It was interesting that I could not put the AM compiler flags at the highest-level Makefile.am file.  It doesn't really matter for this project because there is only one source directory (src).  It would be useful for a project with more than one source directory which I am sure that I was involved with back in the BSD 4.1 days (~40 years ago).  It's amazing how much make & automake lore that I have forgotten!

**Comment by texadactyl** [comment]
Is there some use for the "config.h.in~" file at the highest level?  It looks like a `vi` backup file or some other copy.

**Comment by david-macmahon** [comment]
Yeah, I always forget the rules about when make does or does not propagate various variables.  I think larger projects define common variables in a `common.mk` file and include that from within all the `Makefile.am` files, but in this case the approach you chose is totally appropriate (and preferable, IMHO).

I agree that the `config.h.in~` file looks like a stray backup file that managed to get committed.  Feel free to open another pull request to remove that file and add `*~` to `.gitignore`.  Looks like some new(ish) executables could also be added to `.gitignore`.

**Pull request merged**
